project:
  type: website
  output-dir: docs

editor:
  render-on-save: true

execute:
  freeze: auto

website:
  # title: "Harrison's Website"
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        href: mypw/projects/projects.qmd
      - text: More
        menu:
          - mypw/more/kendama.qmd
      - href: mypw/about.qmd
        text: About Me

  sidebar:
    - id: projects
      title: Projects Overview
      style: floating
      contents:
        - mypw/projects/projects.qmd
        - section: "Projects"
          contents: 
            - mypw/projects/project1.qmd

    - id: japan-itinerary
      title: 日本行
      style: floating
      contents:
        - japan_itinerary/japan.qmd
        - section: "宮崎"
          contents: 
            - japan_itinerary/miyazaki/miyazaki.qmd
            - section: "行程"
              contents: 
              - japan_itinerary/miyazaki/星期一.qmd
              - japan_itinerary/miyazaki/星期二.qmd
              - japan_itinerary/miyazaki/星期三.qmd
              - japan_itinerary/miyazaki/星期四.qmd
            - japan_itinerary/miyazaki/景點.qmd
            - japan_itinerary/miyazaki/food.qmd
    

format:
  html:
    theme:
      light: flatly
      dark: darkly
      # - cosmo
      # - brand
    css: styles.css
    toc: true



