project:
  type: website
  output-dir: docs

editor:
  render-on-save: true

execute:
  freeze: auto

website:
  # title: "Harrison's Website"
  back-to-top-navigation: true
  navbar:
    left:
      - href: mypw/index.qmd
        text: Home
      - text: Projects
        href: mypw/projects/projects.qmd
      - text: More
        menu:
          - mypw/more/kendama.qmd
      - href: mypw/about.qmd
        text: About Me

  sidebar:
    - id: projects
      title: Projects Overview
      style: floating
      contents:
        - mypw/projects/projects.qmd
        - section: "Projects"
          contents: 
            - mypw/projects/project1.qmd
    

format:
  html:
    theme:
      light: flatly
      dark: darkly
      # - cosmo
      # - brand
    css: styles.css
    toc: true



